import rtconfig
from building import *

cwd  = GetCurrentDir()
path = [cwd]
src  = Glob('*.c')
src += Glob('mcusdk/*.c')

group = DefineGroup('Applications', src, depend = [''], CPPPATH = path)

Return('group')
